# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('class_des', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
    ]
