# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_auto_20180424_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_sex',
            field=models.BooleanField(default=0),
        ),
    ]
