# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_auto_20180424_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_chinese',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
